version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - /tmp/dockerdir:/etc/mysql/conf.d/
    ports:
      - 3396:3306
  adminer:
    image: adminer:latest
    ports:
      - "9000:8080"
    depends_on:
      - db

  app:
    build: .
    command: /bin/sh -c "rm -f /sinkaapp/tmp/pids/server.pid && bundle exec bin/rails server -p 3000 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - .:/sinkaapp
      - bundle:/usr/local/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 3020:3000
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  mysql-data:
  bundle:
